### ISSUE TITLE
ClickHouse support

### ISSUE THREAD

**Issue by MahmoudElhalwany** [chaos-genius/chaos_genius#1085]
## Tell us about the problem you're trying to solve
ClickHouse is a widely used OLAP database. So I am looking for adding it somehow as a Datasource.
ClickHouse supports MySQL driver, so we can connect as MySQL clients to it, but it gave me an error when testing the connection.
After investigating the problem, I saw that a query "ROLLBACK" give an exception because no transaction was found.

## Describe the solution you'd like
so it will be helpful to support ClickHouse over MySQL driver or even over HTTP requestor native client.

**Comment by MahmoudElhalwany** [comment]
I am working on it

**Comment by MahmoudElhalwany** [comment]
@Samyak2 should we close this issue ??

**Comment by Samyak2** [comment]
We'll close it when the next version is released

**Comment by Samyak2** [comment]
Added in #1090 (available in v0.10.2)
