### ISSUE TITLE
Anomaly charts do not highlight outliers & CI range in some edge cases

### ISSUE THREAD

**Issue by suranah** [chaos-genius/chaos_genius#154]
It looks like this is only triggered in cases where the first data point is an outlier. May be related to our charting/ intercept code. 

Some Examples:

![image](https://user-images.githubusercontent.com/948291/132459862-e43d5834-68fc-4b31-bb4b-c08091020b09.png)
![image](https://user-images.githubusercontent.com/948291/132460222-e63572c0-5b19-4d49-b8aa-483158e63d62.png)

**Comment by manassolanki** [comment]
Closing this for the time being, please reopen if the issue persist
