### ISSUE TITLE
KPI setup takes too long & shows a blocking loader

### ISSUE THREAD

**Issue by suranah** [chaos-genius/chaos_genius#750]
## Describe the bug
KPI setup takes too long & shows a blocking loader

## Explain the environment
- **Chaos Genius version**:  0.4.0
- **Deployment type**: Docker

## Expected behavior
We should not have a blocking loader. Ideally should also cache or store it. 

## Screenshots
<img width="640" alt="image" src="https://user-images.githubusercontent.com/948291/154789679-1d194433-9700-47f5-b3a2-2376c15eba01.png">

**Comment by manassolanki** [comment]
This is partially fixed on the frontend side. The backend side issues need to be fixed.

**Comment by Samyak2** [comment]
Fixed by prefetching metadata when data source is added and everyday since then. See #858.
