### ISSUE TITLE
Alerts should show numbers in human-readable format

### ISSUE THREAD

**Issue by KShivendu** [chaos-genius/chaos_genius#766]
## Tell us about the problem you're trying to solve
The alerts display numbers without any formatting. For large numbers, this can be difficult to read

## Describe the solution you'd like
The numbers in alerts should be formatted with `M`, `B`, `K` suffixes for Million, Billion, Thousand, etc. as it is shown in the UI.

**Comment by Samyak2** [comment]
This is being added in v0.6.0:
![image](https://user-images.githubusercontent.com/34161949/162360414-4180fee4-82d6-40a0-9762-5308f60ae175.png)
