### ISSUE TITLE
# [FEAT] Support for Timezone Aware Data

### ISSUE THREAD

**Issue by rjdp** [chaos-genius/chaos_genius#794]
# Tell us about the problem you're trying to solve
Support to timezone aware data being ingested from all datasources, right now CG does not support creation of KPIs with tz aware data
# Describe the solution you'd like
Solutions apply to following parts as below:

## 1. KPI Definition
- Based on the datetime column, we need to set a tz-aware flag in the KPI itself
## 2. KPI Validation
- Remove validation steps that currently allows for tz-naive data only
- Add parsing support for ISO formatted timestamps (through pandas). Note: to be also adderessed in Data Loader as well
## 3. Query
- while selecting data using start, end date, make sure these dates are adjusted using Timezone configured in CG
## 4. Data preprocessing
- If tz-aware, Convert all data to given timezone in settings and then Convert to tz-naive

#### Note: Above solution applicable when we encounter tz aware data else regular handling should be applicable

**Comment by Amatullah** [comment]
Added feature. Refer #860, #909 , #910, #913 and #919.
