### ISSUE TITLE
Implement event based alerting

### ISSUE THREAD

**Issue by suranah** [chaos-genius/chaos_genius#90]
### Motivation 

Alerting on changes in the database is an effective way to coordinate escalations when non-ideal scenarios happen. CG does not integrate directly with the database we cannot use CDC systems like debezium or database triggers. So this solution would be focussed on a low-touch setup for business & analyst users via a SQL query that we regularly poll. 

### Assumptions for baseline implementation

1. Not handle SQL queries that result in more than 1000 rows
2. Does not account for table schema changes
3. SQL result output should have a consistent schema for each poll
4. Handle only insertions & deletions (and not updates)
5. Using only local storage for result persistence 
6. Alert types can be changed after setting up the alert

### Proposed Functionality 

Based on alert settings, we will poll the SQL query every X mins, every X hour(s), every day, every week. We will limit results to 1K rows if possible via SQLAlchemy. There will also be a check while adding the alert (for front-end). These results are stored in a pandas dataframe and appropriate action will be taken for each alert type. 

#### 🚨 Alert Types
We will start with only handling three cases:

1. Always Send an Alert
2. Send Alert on Changes (only insertions & deletions, updates to be added in next iteration)
3. Send Alert on Addition (only insertions)

#### 🧮 Logical flow

Flow for the first run (or persisted result key file does not exist):
- If it is always sent, we proceed with the alert flow after persisting the results. 
- For alert on changes or additions we only persist results. 
- Results are persisted via a local pickle file

Flow for susbsequent runs:
- If it is always sent, we proceed with the alert flow after persisting the results. 
- For alert on changes or additions we first compare for changes, generate the alert CSV, then persist latest results. 
  -  For insertion can use 
 `df_new.merge(df_old, how = 'outer' ,indicator=True).loc[lambda x : x['_merge']=='left_only']`
  - For deletion can use 
`df_new.merge(df_old, how = 'outer' ,indicator=True).loc[lambda x : x['_merge']=='right_only']`
- Changes are insertions + deletions 

For alerting:
- Generate a CSV based on alert settings. 
- Send it by email with a title, body, alert file (attached CSV). 

### Questions
1. What should be daily or weekly test & trigger time?
  Add a starting time for each alert if possible. 
2. How do we show changes (insert or delete) in the CSV? 
  Add a cg_status flag at the start of each row that tells whether it’s an insertion or deletion.

**Comment by manassolanki** [comment]
@suranah Closing this since it was implemented long back. Please feel free to reopen if you found anything missing.
