### ISSUE TITLE
[BUG] Editing a KPI gets it removed from every dashboard except `All`.

### ISSUE THREAD

**Issue by varunp2k** [chaos-genius/chaos_genius#965]
## Describe the bug
Dashboard gets reset to `All` when a KPI is edited.

## Explain the environment
- **Chaos Genius version**:  0.7.0
- **OS Version / Instance**: Ubuntu 20.04, AWS EC2
- **Deployment type**:  Bare Bones installation

## Current behavior
Editing a KPI causes the dashboards the KPI belongs to to be reset to `All`

## Expected behavior
The KPI should retain all the dashboards it belongs to even after editing.

**Comment by Samyak2** [comment]
Fixed in v0.8.0
